version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./conf/1:/conf
      - ./data/1:/data
    networks:
      - extnet

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./conf/2:/conf
      - ./data/2:/data
    networks:
      - extnet

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - ./conf/3:/conf
      - ./data/3:/data
    networks:
      - extnet

  web:
    image: elkozmon/zoonavigator-web:latest
    restart: always
    hostname: zoonavigator-web
    ports:
      - 8000:8000
    environment:
      API_PORT: 9000
      API_HOST: "api"
    depends_on:
     - api
    networks:
      - extnet

  api:
    image: elkozmon/zoonavigator-api:latest
    restart: always
    hostname: zoonavigator-api
    environment:
      API_HTTP_PORT: 9000
    depends_on:
     - zoo1
     - zoo2
     - zoo3
    ports:
      - 9000:9000
    networks:
      - extnet

  web_server:
    image: httpd:latest
    restart: always
    hostname: web_server
    ports:
      - 80:80
    deploy:
      mode: global
    depends_on:
      - api
    volumes:
      - ./apache_conf:/usr/local/apache2/conf
    networks:
      - extnet

networks: 
    extnet:
        ipam:
            config:
                - subnet: 192.168.101.0/24
